import { library } from "@fortawesome/fontawesome-svg-core";
import { faGithub, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import {
  faArrowLeft,
  faArrowRight,
  faBrain,
  faCaretDown,
  faChartLine,
  faFileArrowDown,
  faFileShield,
  faGrip,
  faHouse,
  faMoon,
  faPaintRoller,
  faRocket,
  faSearch,
  faStopwatch,
  faSun,
  faTimes,
  faUniversalAccess,
  faUser,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faArrowLeft,
  faArrowRight,
  faStopwatch,
  faBrain,
  faChartLine,
  faHouse,
  faCaretDown,
  faUniversalAccess,
  faFileShield,
  faGithub,
  faRocket,
  faGrip,
  faFileArrowDown,
  faLinkedin,
  faTimes,
  faSearch,
  faPaintRoller,
  faUser,
  faSun,
  faMoon
);
