import { library } from "@fortawesome/fontawesome-svg-core";
import { faGithub, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import {
  faArrowLeft,
  faArrowRight,
  faBook,
  faBrain,
  faCaretDown,
  faChartLine,
  faCircleInfo,
  faFileArrowDown,
  faFileShield,
  faGrip,
  faHouse,
  faMoon,
  faPaintRoller,
  faPlugCirclePlus,
  faRocket,
  faSearch,
  faShapes,
  faSpinner,
  faStopwatch,
  faSun,
  faTimes,
  faUniversalAccess,
  faUser,
  faWeightScale,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faArrowLeft,
  faArrowRight,
  faBrain,
  faCaretDown,
  faChartLine,
  faCircleInfo,
  faFileArrowDown,
  faFileShield,
  faGithub,
  faGrip,
  faHouse,
  faLinkedin,
  faBook,
  faMoon,
  faPaintRoller,
  faPlugCirclePlus,
  faSpinner,
  faRocket,
  faShapes,
  faSearch,
  faStopwatch,
  faSun,
  faTimes,
  faUniversalAccess,
  faUser,
  faWeightScale
);
