name: demo-feedback:test

on:
  workflow_dispatch:

  pull_request:
    branches:
      - master
    paths:
      - "packages/demo-feedback-form/**"
      - "packages/boondoggle.design/**"
      - "packages/gatsby-shared/**"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Run jest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest unit tests
        run: npm run demo-feedback:jest

      - name: Install Firebase tools
        run: npm install -g firebase-tools

      - name: Run Cypress E2E tests
      - run: npm run demo-feedback:cy:run:emulate-firebase
