name: demo-feedback:test

on:
  workflow_dispatch:

  pull_request:
    branches:
      - master
    paths:
      - "packages/demo-feedback-form/**"
      - "packages/boondoggle.design/**"
      - "packages/gatsby-shared/**"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Test
    env:
      # Expose firebase variables to gatsby runtime
      # API keys for Firebase services are not secret
      # https://firebase.google.com/support/guides/security-checklist#api-keys-not-secret
      GATSBY_FIREBASE_WEB_API_KEY: ${{ secrets.GATSBY_FIREBASE_WEB_API_KEY }}
      GATSBY_FIREBASE_AUTH_DOMAIN: ${{ secrets.GATSBY_FIREBASE_AUTH_DOMAIN }}
      GATSBY_FIREBASE_PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_PROJECT_ID }}
      GATSBY_FIREBASE_STORAGE_BUCKET:
        ${{ secrets.GATSBY_FIREBASE_STORAGE_BUCKET }}
      GATSBY_FIREBASE_MESSAGING_SENDER_ID:
        ${{ secrets.GATSBY_FIREBASE_MESSAGING_SENDER_ID }}
      GATSBY_FIREBASE_APP_ID: ${{ secrets.GATSBY_FIREBASE_APP_ID }}
      GATSBY_FIREBASE_MEASUREMENT_ID:
        ${{ secrets.GATSBY_FIREBASE_MEASUREMENT_ID }}
      GATSBY_FIREBASE_DATABASE_URL: ${{ secrets.GATSBY_FIREBASE_DATABASE_URL}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest unit tests
        run: npm run demo-feedback:jest

      - name: Run Cypress E2E tests
        run: npm run demo-feedback:cy:run:emulate-firebase
