on:
  workflow_dispatch
  pull_request:
    branches:
      - master
    paths:
      - "packages/gatsby-site/**"



jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Run jest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run jest:demo-feedback-form
