on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["master"]
    paths:
      - "packages/gatsby-site/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Run jest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm run jest:gatsby-site
